### PR TITLE
Update footer's logo

### PR DESCRIPTION
**Pull request by lebaudantoine**
## Purpose

Align the website with the official logo

## Proposal

Quick and dirty approach to align footer with recent design changes.

### CODE REVIEW

**Comment by lebaudantoine** [comment]
https://github.com/numerique-gouv/lasuite-landingpage/assets/45729124/aada653d-d4c7-4e63-8356-fad2d0fde57a

**Comment by lebaudantoine** [comment]
@manuhabitela I described my choices in the latter commit. The overflow happens for screen smaller than 302px. With the current design, that the quickest solution I found. Let's discuss it on Monday with Johann.

**Comment by manuhabitela** [comment]
Great :) as long as everything is great starting at 320px it's ok for me!

**Review by manuhabitela — APPROVED** [review]

**Comment by manuhabitela** [comment]
On paper we could add some text in the `aria-label` of the footer link with "Gouvernement - Direction interministérielle du numérique" but I'd say it's a bit overkill since the sentence right after it says that already.

Thanks!

**Pull request merged**
